### ISSUE TITLE
help asap not working

### ISSUE THREAD

**Issue by heyeanne34** [adilmohak/django-lms#58]
PS C:\Users\LENOVO Z40\django-lms> python manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\LENOVO Z40\django-lms\manage.py", line 21, in <module>
    main()
  File "C:\Users\LENOVO Z40\django-lms\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py", line 87, in __getattr__
    self._setup(name)
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py", line 74, in _setup  
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\LENOVO Z40\django-lms\config\settings.py", line 125, in <module>
    "NAME": config("DB_NAME"),
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO Z40\AppData\Local\Programs\Python\Python311\Lib\site-packages\decouple.py", line 92, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: DB_NAME not found. Declare it as envvar or define a default value.. i put in .env is DB_NAME=django_sms_data
DB_USER=postgres
DB_PASSWORD=testing321
DB_HOST=localhost
DB_PORT=5432 like in your youu=tube video but it says that please help

**Comment by adilmohak** [comment]
@heyeanne34 Hello, I know this is a late reply but if you are still facing this error I want to let you know that this has been resolved.
